version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true

      - run:
          name: Build Docker image
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build --build-arg GIT_TOKEN="${GIT_TOKEN}" -t clarkzjw/blog.jinwei.me:$TAG .
